---
model: "0.1"
root:
  shape: object
  children:
    mtu:
      shape: scalar
      scalar_type: integer
      access:
        read:
          rules: {}
          contract:
            rules:
              guard:
                access:
                  read:
                    rules: {}
                    contract:
                      rules:
                        guard: {}
