// Package conformance runs the corpus in ../../conformance against the Go
// implementation.
//
// The vectors are implementation-independent (YAML in, YAML out) and this
// runner adds no Go-specific fixture: it reads the same files the Rust
// implementation will read. Where the two disagree, the disagreement is the
// spec's, not the language's.
package conformance

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/CentralInfraCore/cic-object-model/go/objectmodel"
)

const corpus = "../../conformance"

// update rewrites the expectation files from what the implementation produces.
//
// This is the dangerous flag in this repository, and it is worth being explicit
// about why it exists and what stops it being a way to make red go green.
//
// Why it exists: a deliberate change to the canonical form touches every
// expectation at once. Model 0.2 changed 13 of them — the `cic` member left the
// root, the root gained its shape, primitive payloads became node trees — and
// they were regenerated by a one-off script that got three of them subtly
// wrong. Hand-editing at that scale produces mistakes; a mechanical rewrite
// plus a reviewed diff does not.
//
// Why it is not a shortcut: nothing here decides whether a change is correct.
// It writes files into the working tree, and the ONLY thing that makes the new
// expectations real is a human reading `git diff` and committing it. That is
// the review, and it happens where review belongs — on the diff, not on a
// terminal that scrolled past.
//
// Three guards:
//   - it refuses to run when CI is set, so a pipeline can never self-approve
//   - it prints every file it rewrites, so a silent 26-file rewrite is not
//     possible
//   - it fails the run afterwards, so `-update` can never report success; you
//     must re-run the tests normally to see green
var update = flag.Bool("update", false,
	"rewrite conformance expectations from actual output — review the diff before committing")

// updatedFiles records what -update touched, for the summary and the
// deliberate failure at the end of the run.
var updatedFiles []string

func writeExpectation(t *testing.T, path string, content []byte) {
	t.Helper()
	if os.Getenv("CI") != "" {
		t.Fatal("-update refused: CI is set. A pipeline must never rewrite the " +
			"expectations it is checking against.")
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("could not rewrite %s: %v", path, err)
	}
	updatedFiles = append(updatedFiles, path)
	t.Logf("UPDATED %s", path)
}

// TestMain reports what -update did and fails the run on purpose.
func TestMain(m *testing.M) {
	flag.Parse()
	code := m.Run()
	if *update {
		fmt.Fprintf(os.Stderr, "\n=== -update rewrote %d expectation file(s) ===\n", len(updatedFiles))
		for _, f := range updatedFiles {
			fmt.Fprintf(os.Stderr, "  %s\n", f)
		}
		fmt.Fprintf(os.Stderr, "\nNothing is verified yet. Read `git diff`, decide whether every\n"+
			"change is one you meant, then re-run the tests without -update.\n")
		// Never exit 0 in update mode: a green -update run would be a result
		// nobody checked.
		code = 1
	}
	os.Exit(code)
}

// expectedCounts is what "the corpus ran" means. A runner that discovers zero
// vectors and exits 0 has not run the corpus, so the counts are asserted
// rather than reported.
var expectedCounts = map[string]int{
	"materialization": 13,
	// 7 since model 0.2: `invalid/008_cyclic_primitive_declaration` was
	// removed. It asserted that a repeated primitive name is a cycle, which
	// INV-005 no longer treats as one — under INV-035 a primitive's payload
	// materializes like any other structure, so that nesting is ordinary.
	// See docs/spec-defects.md SD-005.
	"invalid": 7,
	// 9 since the origin grammar became enforced: 007, 008 and 009 are the
	// negative side of INV-013. The invariant says "exactly four forms" and was
	// covered by four vectors, one per form, all positive — so the corpus
	// asserted that the four are accepted and never that a fifth is refused.
	// [yaml, yaml] and [schema, sealed(t,p)] passed against that corpus.
	"validation": 9,
}

type expectedError struct {
	Error struct {
		Code      string `yaml:"code"`
		Invariant string `yaml:"invariant"`
		Stage     string `yaml:"stage"`
		Path      string `yaml:"path"`
		Detail    string `yaml:"detail"`
	} `yaml:"error"`
}

func vectors(t *testing.T, group string) []string {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(corpus, group))
	if err != nil {
		t.Fatalf("cannot read the %s vectors: %v", group, err)
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			names = append(names, e.Name())
		}
	}
	if got, want := len(names), expectedCounts[group]; got != want {
		t.Fatalf("%s: discovered %d vectors, expected %d", group, got, want)
	}
	return names
}

func read(t *testing.T, parts ...string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(parts...))
	if err != nil {
		t.Fatalf("cannot read %s: %v", filepath.Join(parts...), err)
	}
	return b
}

// TestCorpusSize fails if the corpus on disk is not the corpus expectedCounts
// describes.
//
// The total used to be a second literal alongside the per-group map, and the
// two drifted exactly as duplicated facts do: the comment said 27, the literal
// said 26, and the map summed to 26. It is derived now, so the counts live in
// one place.
//
// What the derivation cannot catch is a group that exists on disk and not in
// the map — the loops only ever visit the map's keys, so a whole directory of
// vectors could sit there unexecuted. That is checked separately below, and it
// is the same failure shape as the manifest gate that could not see a file it
// did not list.
func TestCorpusSize(t *testing.T) {
	entries, err := os.ReadDir(corpus)
	if err != nil {
		t.Fatalf("reading the corpus root: %v", err)
	}
	onDisk := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() {
			onDisk[e.Name()] = true
		}
	}
	for group := range onDisk {
		if _, known := expectedCounts[group]; !known {
			t.Errorf("conformance/%s/ exists but no runner claims it; its vectors never run", group)
		}
	}
	for group := range expectedCounts {
		if !onDisk[group] {
			t.Errorf("expectedCounts names %q, which is not in the corpus", group)
		}
	}

	total, want := 0, 0
	for group, n := range expectedCounts {
		total += len(vectors(t, group))
		want += n
	}
	if total != want {
		t.Fatalf("discovered %d vectors, expectedCounts describes %d", total, want)
	}
	t.Logf("corpus: %d vectors", total)
}

// TestMaterialization runs conformance/materialization/*: authoring input to
// canonical object.
func TestMaterialization(t *testing.T) {
	for _, name := range vectors(t, "materialization") {
		dir := filepath.Join(corpus, "materialization", name)
		t.Run(name, func(t *testing.T) {
			schema := read(t, dir, "schema.yaml")
			input := read(t, dir, "input.yaml")
			expected := read(t, dir, "expected.yaml")

			obj, err := objectmodel.Materialize(schema, input)
			if err != nil {
				t.Fatalf("materialization failed: %v", err)
			}

			// SPEC §10: the output must match expected.yaml exactly. §8.8
			// never defines a canonical serialization, so "exactly" can only
			// be checked semantically — see docs/spec-defects.md SD-010.
			var got, want any
			if err := yaml.Unmarshal(obj.CanonicalYAML(), &got); err != nil {
				t.Fatalf("canonical output is not valid YAML: %v", err)
			}
			if err := yaml.Unmarshal(expected, &want); err != nil {
				t.Fatalf("expected.yaml is not valid YAML: %v", err)
			}
			if !reflect.DeepEqual(got, want) {
				if *update {
					writeExpectation(t, filepath.Join(dir, "expected.yaml"),
						append([]byte("---\n"), corpusStyle(obj.CanonicalYAML())...))
				} else {
					t.Errorf("canonical object does not match expected.yaml\n--- got ---\n%s\n--- want ---\n%s",
						obj.CanonicalYAML(), expected)
				}
			}

			// INV-030 — the same schema and input must produce a
			// byte-identical canonical object.
			again, err := objectmodel.Materialize(schema, input)
			if err != nil {
				t.Fatalf("second materialization failed: %v", err)
			}
			if !reflect.DeepEqual(obj.CanonicalYAML(), again.CanonicalYAML()) {
				t.Errorf("INV-030: materialization is not deterministic")
			}
		})
	}
}

// TestInvalid runs conformance/invalid/*: authoring input that must be
// rejected, with the right code at the right stage.
func TestInvalid(t *testing.T) {
	for _, name := range vectors(t, "invalid") {
		dir := filepath.Join(corpus, "invalid", name)
		t.Run(name, func(t *testing.T) {
			schema := read(t, dir, "schema.yaml")
			input := read(t, dir, "input.yaml")

			var want expectedError
			if err := yaml.Unmarshal(read(t, dir, "expected-error.yaml"), &want); err != nil {
				t.Fatalf("expected-error.yaml is not valid YAML: %v", err)
			}

			_, err := objectmodel.Materialize(schema, input)
			assertRejected(t, dir, err, want)
		})
	}
}

// TestValidation runs conformance/validation/*: an already-canonical object
// presented to SPEC §8.7 directly.
func TestValidation(t *testing.T) {
	for _, name := range vectors(t, "validation") {
		dir := filepath.Join(corpus, "validation", name)
		t.Run(name, func(t *testing.T) {
			object := read(t, dir, "object.yaml")

			var want expectedError
			if err := yaml.Unmarshal(read(t, dir, "expected-error.yaml"), &want); err != nil {
				t.Fatalf("expected-error.yaml is not valid YAML: %v", err)
			}

			assertRejected(t, dir, objectmodel.ValidateCanonicalDocument(object), want)
		})
	}
}

func assertRejected(t *testing.T, dir string, err error, want expectedError) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected rejection %s at stage %s, got none",
			want.Error.Code, want.Error.Stage)
	}
	var got *objectmodel.Error
	if !errors.As(err, &got) {
		t.Fatalf("expected an *objectmodel.Error, got %T: %v", err, err)
	}
	if got.Code != want.Error.Code {
		t.Errorf("code: got %s, want %s", got.Code, want.Error.Code)
	}
	if got.Invariant != want.Error.Invariant {
		t.Errorf("invariant: got %s, want %s", got.Invariant, want.Error.Invariant)
	}
	// conformance/README.md: "Rejecting with the right code at the wrong
	// stage is a failure: stage order is normative (§8)."
	if string(got.Stage) != want.Error.Stage {
		t.Errorf("stage: got %s, want %s", got.Stage, want.Error.Stage)
	}
	if got.Path != want.Error.Path {
		t.Errorf("path: got %s, want %s", got.Path, want.Error.Path)
	}

	// -update rewrites the expectation only when something actually differs,
	// and only the four asserted fields plus the detail. The `detail` text is
	// prose for a human and is regenerated with the rest; nothing asserts on it.
	if *update && t.Failed() {
		rewriteExpectedError(t, dir, got, want)
	}
}

// corpusStyle rewrites origin lists to the inline form the corpus is written
// in, so an -update diff shows semantic changes and not a formatting churn
// across every line. The comparison is semantic either way (§8.8 defines no
// canonical serialization — docs/spec-defects.md SD-010), so this is purely so
// the diff stays readable, which is the whole point of the flag.
func corpusStyle(b []byte) []byte {
	lines := strings.Split(string(b), "\n")
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimRight(lines[i], " ")
		if !strings.HasSuffix(trimmed, "origin:") {
			out = append(out, lines[i])
			continue
		}
		indent := trimmed[:len(trimmed)-len("origin:")]
		var terms []string
		j := i + 1
		for ; j < len(lines); j++ {
			item := strings.TrimSpace(lines[j])
			if !strings.HasPrefix(item, "- ") || !strings.HasPrefix(lines[j], indent+"  - ") {
				break
			}
			terms = append(terms, strings.TrimSpace(item[2:]))
		}
		if terms == nil {
			// A sealed origin is a mapping, not a scalar list; leave it alone.
			out = append(out, lines[i])
			continue
		}
		out = append(out, indent+"origin: ["+strings.Join(terms, ", ")+"]")
		i = j - 1
	}
	return []byte(strings.Join(out, "\n"))
}

// rewriteExpectedError regenerates expected-error.yaml from the error the
// implementation actually raised.
//
// The address grammar change of model 0.2 rewrote all 13 of these by hand and
// three came out wrong, each one a case where a path segment names a node
// member rather than a payload child. A mechanical rewrite cannot make that
// mistake; a reviewer reading the diff still has to decide whether the new
// path is the RIGHT one, which is the part no tool can do.
func rewriteExpectedError(t *testing.T, dir string, got *objectmodel.Error, want expectedError) {
	t.Helper()
	out := fmt.Sprintf(`---
error:
  code: %s
  invariant: %s
  stage: %s
  path: %s
  detail: >-
    %s
`, got.Code, got.Invariant, got.Stage, got.Path, got.Detail)
	writeExpectation(t, filepath.Join(dir, "expected-error.yaml"), []byte(out))
}
